theme: jekyll-theme-minimal

title: Salesforce Offline Setup Assistant
description: >-
  Documentation for the Salesforce Offline Setup Assistant. 
  An unofficial offline simulator for exploring Salesforce CRM features without needing cloud access.

# SEO Settings
# twitter:
#   username: your_twitter_handle
#   card: summary
# logo: logo.png
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/your_twitter_handle
#     - https://github.com/your_github_handle 